#!/bin/sh

cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
esac

SVNKIT_HOME=`dirname $0`
SVNKIT_HOME=`cd "$SVNKIT_HOME" ; pwd`
SVNKIT_VER=`ls $SVNKIT_HOME/svnkit-cli-* | cat | sed -e 's/^.*svnkit-cli-//' | sed -e 's/.jar//'`
echo "SVNKit version $SVNKIT_VER"

SVNKIT_CP="$SVNKIT_HOME/svnkit-$SVNKIT_VER.jar":"$SVNKIT_HOME/svnkit-cli-$SVNKIT_VER.jar":"$SVNKIT_HOME/svnkit-trilead-$SVNKIT_VER.jar":"$SVNKIT_HOME/svnkit-jna-$SVNKIT_VER.jar"

if $cygwin ; then
  SVNKIT_CP=`cygpath --windows --path "$SVNKIT_CP"`
fi

SVNKIT_VM_OPTIONS="-Dsun.io.useCanonCaches=false -Djava.util.logging.config.file=$SVNKIT_HOME/logging.properties"

SVNKIT_MAINCLASS=org.tmatesoft.svn.cli.SVN
"$JAVA_HOME/bin/java" $SVNKIT_VM_OPTIONS -cp $SVNKIT_CP $SVNKIT_MAINCLASS "$@"
